### ISSUE TITLE
Error in vtapi class

### ISSUE THREAD

**Issue by PacoH** [Erethon/vta.py#1]
```
$ python ./vtwrapper.py
Traceback (most recent call last):
  File "./vtwrapper.py", line 7, in <module>
    from vta import vtapi
  File "/Users/user/Downloads/VirusTotal API implementation/vta.py-master/vta.py", line 30
    print "Url/file not found, or scanned yet. Try again later"
SyntaxError: invalid syntax
```

**Comment by Erethon** [comment]
I'm guessing you're using python 3? This should work with python 2, but
this project isn't really maintained, the last commit was more than two
years ago.

**Comment by PacoH** [comment]
I just tried it again after uninstalling python3. If I use
 `python vtwrapper.py -f <file>`
I get
`python3: command not found`
But if I use
`/usr/local/bin/python`
it works.
So something's wrong with my 2.7 installation.
